fake_input = {
    "process_performers_json_input": {
        "server_connection": {
            "Scheme": "http",
            "Host": "0.0.0.0",
            "Port": 6969,
            "SessionCookie": {
                "Name": "session",
                "Value": "MTcyMTYyMTM3NHxEdi1CQkFFQ180SUFBUkFCRUFBQWJQLUNBQUlHYzNSeWFXNW5EQWdBQm5WelpYSkpSQVp6ZEhKcGJtY01Cd0FGYzNSaGMyZ0djM1J5YVc1bkRCVUFFM1pwYzJsMFpXUlFiSFZuYVc1elNHOXZhM01iVzExelpYTnphVzl1TGxacGMybDBaV1JRYkhWbmFXNUliMjlyXzRVQ0FRTF9oZ0FCXzRRQUFEbl9nd01CQVJGV2FYTnBkR1ZrVUd4MVoybHVTRzl2YXdIX2hBQUJBZ0VJVUd4MVoybHVTVVFCREFBQkNFaHZiMnRVZVhCbEFRd0FBQUFGXzRZQ0FBQT186pBPyEw-cO2ZZ6s-vY6u0gETeT6CdUy7kmj9cmSTFkE=",
                "Path": "",
                "Domain": "",
                "Expires": "0001-01-01T00:00:00Z",
                "RawExpires": "",
                "MaxAge": 0,
                "Secure": False,
                "HttpOnly": False,
                "SameSite": 0,
                "Raw": "",
                "Unparsed": None,
            },
            "Dir": "H:\\Stash",
            "PluginDir": "H:\\Stash\\plugins\\performerSceneCompare",
        },
        "args": {"mode": "process_performers"},
    },
    "scene_update_json_input": {
        "server_connection": {
            "Scheme": "http",
            "Host": "0.0.0.0",
            "Port": 6969,
            "SessionCookie": {
                "Name": "session",
                "Value": "MTcyMTYyMTM3NHxEdi1CQkFFQ180SUFBUkFCRUFBQWJQLUNBQUlHYzNSeWFXNW5EQWdBQm5WelpYSkpSQVp6ZEhKcGJtY01Cd0FGYzNSaGMyZ0djM1J5YVc1bkRCVUFFM1pwYzJsMFpXUlFiSFZuYVc1elNHOXZhM01iVzExelpYTnphVzl1TGxacGMybDBaV1JRYkhWbmFXNUliMjlyXzRVQ0FRTF9oZ0FCXzRRQUFEbl9nd01CQVJGV2FYTnBkR1ZrVUd4MVoybHVTRzl2YXdIX2hBQUJBZ0VJVUd4MVoybHVTVVFCREFBQkNFaHZiMnRVZVhCbEFRd0FBQUFGXzRZQ0FBQT186pBPyEw-cO2ZZ6s-vY6u0gETeT6CdUy7kmj9cmSTFkE=",
                "Path": "",
                "Domain": "",
                "Expires": "0001-01-01T00:00:00Z",
                "RawExpires": "",
                "MaxAge": 0,
                "Secure": False,
                "HttpOnly": False,
                "SameSite": 0,
                "Raw": "",
                "Unparsed": None,
            },
            "Dir": "H:\\Stash",
            "PluginDir": "H:\\Stash\\plugins\\performerSceneCompare",
        },
        "args": {
            "hookContext": {
                "id": 15995,
                "type": "Scene.Update.Post",
                "input": {
                    "clientMutationId": None,
                    "id": "15995",
                    "title": "Fondling Eva",
                    "code": "",
                    "details": "Freckles, golden skin, and a dazzling smile that lights up the world, Eva Lovia is as bright as the sunshine that pours in like molten gold, all over this gorgeous outdoor setting. Eva's enjoying the tranquility of a quiet afternoon in the yard to make lo...",
                    "director": "",
                    "url": None,
                    "urls": ["https://www.babes.com/scene/3090161/fondling-eva"],
                    "date": "2013-10-15",
                    "rating100": None,
                    "o_counter": None,
                    "organized": None,
                    "studio_id": "41",
                    "gallery_ids": [],
                    "performer_ids": ["392"],
                    "movies": [],
                    "tag_ids": [],
                    "cover_image": None,
                    "stash_ids": [
                        {
                            "stash_id": "0b9fa103-9c04-4e6e-bcc1-a20eafb0669a",
                            "endpoint": "https://stashdb.org/graphql",
                        }
                    ],
                    "resume_time": None,
                    "play_duration": None,
                    "play_count": None,
                    "primary_file_id": None,
                },
                "inputFields": [
                    "code",
                    "title",
                    "details",
                    "stash_ids",
                    "tag_ids",
                    "movies",
                    "performer_ids",
                    "urls",
                    "id",
                    "studio_id",
                    "gallery_ids",
                    "director",
                    "date",
                ],
            }
        },
    },
}
